name: Build

concurrency: 
  group: "build"
  cancel-in-progress: true

on:
  push:
    paths-ignore:
      - '*.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: "src"

      - name: Prepares executable
        run: chmod +x $GITHUB_WORKSPACE/src/gradlew

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build Plugins
        run: |
          cd $GITHUB_WORKSPACE/src
          ./gradlew make makePluginsJson

      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: compiled-plugins
          path: |
            src/**/build/*.cs3
            src/build/plugins.json
