name: Build

concurrency: 
  group: "build"
  cancel-in-progress: true

on:
  push:
    paths-ignore:
      - '*.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: "src"

      - name: Prepares executable
        run: chmod +x $GITHUB_WORKSPACE/src/gradlew

      - name: Checkout builds
        uses: actions/checkout@v4
        with:
          ref: "builds"
          path: "builds"

      - name: Clean old builds
        run: rm $GITHUB_WORKSPACE/builds/*.cs3 || true

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build Plugins
        run: |
          cd $GITHUB_WORKSPACE/src
          ./gradlew makePluginsJson
          mkdir -p $GITHUB_WORKSPACE/builds
          cp build/*.cs3 $GITHUB_WORKSPACE/builds/ || true
          cp build/plugins.json $GITHUB_WORKSPACE/builds/ || true

      - name: Push builds
        run: |
          cd $GITHUB_WORKSPACE/builds
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Build plugins" || exit 0
          git push
