name: Build Plugins

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          path: "src"

      - name: Checkout Builds Branch
        uses: actions/checkout@v4
        with:
          ref: "builds"
          path: "builds"

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Clean old builds
        run: |
          rm -f builds/*.cs3 || true
          rm -f builds/*.jar || true

      - name: Build Plugins
        run: |
          cd src
          chmod +x gradlew
          ./gradlew makePluginsJson
          cp **/build/*.cs3 ../builds/ || true
          cp build/plugins.json ../builds/ || true

      - name: Push builds
        run: |
          cd builds
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "Build"
          git push
